In [1]:
import numpy as np
from keras.datasets import mnist

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [3]:
x_train.shape

(60000, 28, 28)

In [4]:
images = x_train[:1000].reshape(1000, 28*28)
labels = y_train[0:1000].reshape(1000,1)

In [6]:
labels[:10]

array([[5],
       [0],
       [4],
       [1],
       [9],
       [2],
       [1],
       [3],
       [1],
       [4]], dtype=uint8)

In [16]:
ind = [(0,2),(1,3)]
arr = np.random.rand(4,5)
print(arr)
print(arr[[0,1,2], [2,3,2]])

[[0.0187774  0.40096562 0.54397182 0.12717579 0.76348997]
 [0.72280741 0.46041439 0.71211558 0.08315773 0.36394686]
 [0.53631626 0.29903702 0.3449732  0.83723477 0.64912785]
 [0.81546561 0.28126664 0.56158202 0.19636561 0.65864796]]
[0.54397182 0.08315773 0.3449732 ]


In [17]:

arr = [1,2,3,4]
arr[::-1]

[4, 3, 2, 1]